name: Destroy Mission Enclave Managment plan [USE WITH CAUTION]

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:    
    runs-on: ubuntu-latest
    name: Destroy terraform configuration plan for an Mission Enclave Management terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
      ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform destroy
        uses: azurenoops/terraform-github-actions/terraform-destroy@v1.34.2
        with:
          path: infrastructure/terraform
          variables: |
            keyvault_admins_group_object_id = "${{ secrets.AZURE_ADMINS_GROUP_OBJECT_ID }}" 
            subscription_id_hub               = "${{ env.ARM_SUBSCRIPTION_ID }}"
            subscription_id_identity          = "${{ secrets.AZURE_IDENTITY_SUBSCRIPTION_ID }}" 
            subscription_id_operations        = "${{ secrets.AZURE_OPERATIONS_SUBSCRIPTION_ID }}"
            subscription_id_security          = "${{ secrets.AZURE_SECURITY_SUBSCRIPTION_ID }}" 
            subscription_id_forensic          = "${{ secrets.AZURE_FORENSIC_SUBSCRIPTION_ID }}"
            subscription_id_devsecops         = "${{ secrets.AZURE_DEVSECOPS_SUBSCRIPTION_ID }}"
            vm_admin_password                 = "${{ env.VM_PASSWORD }}"           
          var_file: |
            infrastructure/terraform/tfvars/parameters.dev.gov.tfvars
          backend_config: |
            storage_account_name=${{ secrets.AZURE_TF_STATE_STORAGE_ACCOUNT_NAME }}
            container_name=${{ secrets.AZURE_TF_STATE_STORAGE_CONTAINER_NAME }}            
            resource_group_name=${{ secrets.AZURE_TF_STATE_RESOURCE_GROUP_NAME }}
