name: Validate terraform on pull request

on:
  - pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate
        uses: azurenoops/terraform-github-actions/terraform-validate@v1.34.2
        with:
          path: infrastructure/terraform